name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Build React App
        run: npm run build

      - name: Build Docker Image
        run: |
          docker build -t coreui-app:${{ github.sha }} .
